version: '3.1'

services:

  wordpress:
    image: wordpress:5.5.3
    ports:
    - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: th221146_project
      WORDPRESS_DB_USER: th221146_project
      WORDPRESS_DB_PASSWORD: "2sNs!+g8A9"
      WORDPRESS_DEBUG: 1
      WORDPRESS_AUTH_KEY: "dsbrfbwdverbvwberbwbwebwevwer"
      WORDPRESS_SECURE_AUTH_KEY: "wegewgewgwegewgewgwergw"
      WORDPRESS_LOGGED_IN_KEY: "gervewhet4ewafewhtejhgqweg"
      WORDPRESS_NONCE_KEY: "hrehwetrjtk6uykuyolyujh5345hh45"
      WORDPRESS_AUTH_SALT: "vsdbny554yjm766k5jthgerh"
      WORDPRESS_SECURE_AUTH_SALT: "rebg4th45765ujthre4h44h"
      WORDPRESS_LOGGED_IN_SALT: "jytkyukmew3464554uhtj45j54"
      WORDPRESS_NONCE_SALT: "gntrmythhl8uyk56u54y5y5y45y"
      WORDPRESS_TABLE_PREFIX: xzebra_
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_DEBUG_LOG', true );
        define( 'WP_DEBUG_DISPLAY', true );
        define( 'ALLOW_UNFILTERED_UPLOADS', true );
    volumes:
    - wordpress:/var/www/html
    - ./theme:/var/www/html/wp-content/themes/projects/
    - ./plugins:/var/www/html/wp-content/plugins/
    - ./uploads:/var/www/html/wp-content/uploads/
    - ./languages:/var/www/html/wp-content/languages/

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: th221146_project
      MYSQL_USER: th221146_project
      MYSQL_PASSWORD: "2sNs!+g8A9"
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=th221146_project
      - PMA_PASSWORD=2sNs!+g8A9
    ports:
      - 8888:80
    volumes:
      - /sessions

volumes:
  wordpress: